name: Deploy Next.js site to GitHub Pages

on:
  # main 브랜치에 푸시할 때마다 실행
  push:
    branches: ["master"]
  # Actions 탭에서 수동으로 워크플로우 실행 가능하게 설정
  workflow_dispatch:

# GITHUB_TOKEN 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시에 하나의 배포만 허용
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 저장소
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: 의존성 설치
        run: yarn install --frozen-lockfile

      - name: Next.js 빌드
        run: yarn build

      - name: GitHub Pages 설정
        uses: actions/configure-pages@v5

      - name: 빌드 결과물 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # 배포 작업
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages에 배포
        id: deployment
        uses: actions/deploy-pages@v4
